# Synthetic Data Generation

## 1. Imports and Setup

In [90]:
from sqlalchemy  import create_engine

In [ ]:
username = "postgres"
password = "YOUR_PASSWORD"
host = "localhost"
port = "5432"
database = "cnc_tool_wear_analysis"

In [92]:
connection_string = f"postgresql+psycopg://{username}:{password}@{host}:{port}/{database}"

In [93]:
engine=create_engine(connection_string)

In [94]:
import pandas as pd

In [95]:
tools_df=pd.read_sql("SELECT * FROM tools",engine)
machines_df=pd.read_sql("SELECT * FROM machines",engine)
operators_df=pd.read_sql("SELECT * FROM operators",engine)
workorders_df=pd.read_sql("SELECT * FROM work_orders",engine)
toolpositions_df=pd.read_sql("SELECT * FROM tool_positions",engine)

## 2. Master Data Generation

In [96]:
import random

In [97]:
random.choice(tools_df["insert_shape"])

'Romboid'

In [98]:
rows=[]
for i in range(100):
    operation_id= f"{i:04d}"
    work_order_id= random.choice(workorders_df["work_order_id"].tolist())
    machine_id= random.choice(machines_df["machine_id"].tolist())
    operator_id= random.choice(operators_df["operator_id"].tolist())
    parts= random.randint(20,100)
    cutting_time= random.uniform(1,10)
    rpm=random.randint(800,3500)

    rows.append([operation_id,work_order_id,machine_id,operator_id,parts,cutting_time,rpm])

In [99]:
rows

[['0000', 'W004', 'M003', 'OP003', 89, 4.310777984970285, 3316],
 ['0001', 'W005', 'M006', 'OP007', 21, 6.302662265079133, 2103],
 ['0002', 'W009', 'M001', 'OP009', 69, 3.298382057088065, 1551],
 ['0003', 'W004', 'M001', 'OP009', 63, 2.762763595639067, 3456],
 ['0004', 'W002', 'M001', 'OP005', 95, 5.949591468018783, 2805],
 ['0005', 'W009', 'M005', 'OP001', 78, 8.681530849548302, 1406],
 ['0006', 'W008', 'M002', 'OP004', 83, 1.9141561834759429, 2311],
 ['0007', 'W010', 'M007', 'OP009', 86, 9.567311008155304, 1273],
 ['0008', 'W010', 'M001', 'OP010', 98, 5.879297055021452, 1424],
 ['0009', 'W006', 'M007', 'OP002', 96, 5.196205134086466, 2107],
 ['0010', 'W005', 'M007', 'OP010', 77, 8.417104559567758, 1257],
 ['0011', 'W008', 'M002', 'OP009', 80, 3.2319795680157095, 1028],
 ['0012', 'W010', 'M001', 'OP006', 78, 6.869692025591908, 816],
 ['0013', 'W004', 'M004', 'OP008', 88, 2.1136235421950937, 3345],
 ['0014', 'W009', 'M007', 'OP001', 79, 9.032122255990476, 1201],
 ['0015', 'W004', 'M005', 'OP002', 59, 1.8945074410451328, 1652],
 ['0016', 'W010', 'M006', 'OP002', 53, 5.907288178864416, 1672],
 ['0017', 'W002', 'M007', 'OP010', 63, 2.2742925886041148, 2455],
 ['0018', 'W008', 'M004', 'OP003', 86, 5.10514957197757, 2972],
 ['0019', 'W004', 'M002', 'OP008', 53, 9.404963749370278, 2855],
 ['0020', 'W003', 'M003', 'OP002', 77, 8.630723192263211, 1619],
 ['0021', 'W008', 'M003', 'OP006', 41, 8.658533916968878, 3161],
 ['0022', 'W002', 'M003', 'OP002', 44, 6.583811832544522, 1696],
 ['0023', 'W010', 'M001', 'OP006', 68, 6.1727258615867795, 2774],
 ['0024', 'W005', 'M005', 'OP007', 23, 3.2545502599423672, 2079],
 ['0025', 'W003', 'M005', 'OP007', 68, 1.0992291587939707, 2656],
 ['0026', 'W002', 'M002', 'OP003', 20, 2.596532937989987, 1377],
 ['0027', 'W001', 'M006', 'OP010', 99, 3.166539670366743, 1312],
 ['0028', 'W003', 'M001', 'OP006', 51, 5.87479092044002, 1436],
 ['0029', 'W004', 'M004', 'OP009', 79, 6.430250386045714, 2609],
 ['0030', 'W003', 'M005', 'OP009', 42, 8.899274522352751, 872],
 ['0031', 'W007', 'M001', 'OP006', 52, 4.257613982704838, 2562],
 ['0032', 'W004', 'M003', 'OP004', 59, 2.446903282794414, 2227],
 ['0033', 'W008', 'M004', 'OP004', 86, 4.667114874447607, 3032],
 ['0034', 'W001', 'M003', 'OP010', 59, 6.106880746396226, 896],
 ['0035', 'W003', 'M007', 'OP001', 89, 9.285666887474447, 1238],
 ['0036', 'W009', 'M002', 'OP003', 30, 7.056565423634592, 2998],
 ['0037', 'W009', 'M007', 'OP004', 28, 7.805179159611061, 1188],
 ['0038', 'W003', 'M001', 'OP010', 38, 9.683157820371441, 2569],
 ['0039', 'W010', 'M003', 'OP010', 35, 4.693763333285715, 1064],
 ['0040', 'W004', 'M001', 'OP007', 80, 7.983525242663169, 1070],
 ['0041', 'W001', 'M007', 'OP001', 97, 6.000417150218979, 1895],
 ['0042', 'W007', 'M007', 'OP009', 39, 7.104994666243345, 2233],
 ['0043', 'W009', 'M004', 'OP006', 21, 6.623870669199906, 2971],
 ['0044', 'W002', 'M005', 'OP004', 100, 5.199245657597848, 2804],
 ['0045', 'W008', 'M004', 'OP008', 38, 8.426623679904717, 1400],
 ['0046', 'W009', 'M003', 'OP009', 59, 2.0014601616499106, 3335],
 ['0047', 'W008', 'M003', 'OP009', 38, 9.449996269284688, 1923],
 ['0048', 'W004', 'M002', 'OP003', 77, 3.2714019611514686, 1085],
 ['0049', 'W008', 'M006', 'OP007', 82, 1.2965477692213905, 2653],
 ['0050', 'W001', 'M003', 'OP001', 99, 5.048261609672232, 3032],
 ['0051', 'W007', 'M002', 'OP005', 74, 1.2836628661503309, 1482],
 ['0052', 'W006', 'M001', 'OP008', 88, 3.1735082353522217, 1629],
 ['0053', 'W003', 'M003', 'OP009', 46, 5.337459934175093, 1643],
 ['0054', 'W006', 'M005', 'OP004', 29, 1.3758569842003854, 917],
 ['0055', 'W010', 'M005', 'OP010', 56, 8.18847614027551, 3222],
 ['0056', 'W003', 'M003', 'OP005', 38, 5.789505702864698, 2429],
 ['0057', 'W004', 'M003', 'OP004', 60, 2.056645212319, 1283],
 ['0058', 'W008', 'M001', 'OP010', 38, 2.285560124983811, 3215],
 ['0059', 'W005', 'M007', 'OP004', 38, 1.434157994265538, 1629],
 ['0060', 'W006', 'M007', 'OP010', 40, 3.4907383208852143, 3124],
 ['0061', 'W010', 'M004', 'OP005', 30, 2.289844053959106, 3099],
 ['0062', 'W010', 'M004', 'OP009', 44, 9.620322239653202, 1909],
 ['0063', 'W003', 'M002', 'OP010', 34, 9.298443204603078, 3159],
 ['0064', 'W004', 'M005', 'OP007', 70, 1.8575400843135315, 2296],
 ['0065', 'W009', 'M003', 'OP007', 27, 2.2139509971287477, 2806],
 ['0066', 'W005', 'M006', 'OP009', 33, 6.285951873867621, 2771],
 ['0067', 'W003', 'M001', 'OP004', 66, 9.766053107808144, 2461],
 ['0068', 'W004', 'M004', 'OP007', 56, 5.047312193752189, 2480],
 ['0069', 'W010', 'M001', 'OP001', 23, 3.918509370105057, 2755],
 ['0070', 'W004', 'M007', 'OP001', 24, 6.9701444852865, 1667],
 ['0071', 'W006', 'M005', 'OP009', 21, 2.9893476747786947, 1280],
 ['0072', 'W009', 'M003', 'OP009', 79, 2.4088950235762874, 2484],
 ['0073', 'W009', 'M007', 'OP007', 43, 3.9082409538762315, 2153],
 ['0074', 'W001', 'M001', 'OP005', 84, 1.8343574923002675, 1372],
 ['0075', 'W009', 'M002', 'OP005', 83, 3.6019196228370096, 2537],
 ['0076', 'W010', 'M003', 'OP009', 95, 9.606269509740612, 1084],
 ['0077', 'W003', 'M007', 'OP006', 90, 9.427144245837328, 1632],
 ['0078', 'W008', 'M003', 'OP006', 28, 3.7812479167764086, 2307],
 ['0079', 'W007', 'M004', 'OP010', 77, 1.1225377489181785, 2474],
 ['0080', 'W002', 'M005', 'OP003', 56, 4.385926713621197, 1955],
 ['0081', 'W002', 'M005', 'OP006', 22, 7.554827052115933, 1970],
 ['0082', 'W005', 'M001', 'OP002', 87, 4.0189362579883525, 1813],
 ['0083', 'W007', 'M004', 'OP005', 24, 2.4652382842126275, 1652],
 ['0084', 'W007', 'M003', 'OP002', 73, 2.960285300406679, 1878],
 ['0085', 'W003', 'M005', 'OP009', 83, 5.614138669296566, 3195],
 ['0086', 'W003', 'M006', 'OP008', 57, 8.883945237439072, 1071],
 ['0087', 'W001', 'M003', 'OP001', 70, 5.817050637712116, 1727],
 ['0088', 'W007', 'M002', 'OP005', 33, 1.282687003023971, 3420],
 ['0089', 'W008', 'M002', 'OP007', 91, 2.3023091178764514, 2722],
 ['0090', 'W010', 'M005', 'OP005', 32, 3.0837024106622497, 1859],
 ['0091', 'W009', 'M003', 'OP006', 20, 8.845622922032671, 2993],
 ['0092', 'W007', 'M003', 'OP007', 43, 6.375803804752021, 2143],
 ['0093', 'W003', 'M001', 'OP009', 22, 8.439307100202363, 3254],
 ['0094', 'W001', 'M006', 'OP004', 88, 6.731901734643138, 3124],
 ['0095', 'W007', 'M006', 'OP005', 40, 5.901229138255876, 3340],
 ['0096', 'W008', 'M006', 'OP008', 33, 8.271549070285857, 1976],
 ['0097', 'W004', 'M006', 'OP004', 33, 5.282342954228386, 1164],
 ['0098', 'W006', 'M007', 'OP009', 88, 3.8314809527654488, 1322],
 ['0099', 'W001', 'M005', 'OP010', 47, 8.480062150721224, 2242]]

In [100]:
operations_df=pd.DataFrame(rows)

In [101]:
operations_df.head()

      0     1     2      3   4         5     6
0  0000  W004  M003  OP003  89  4.310778  3316
1  0001  W005  M006  OP007  21  6.302662  2103
2  0002  W009  M001  OP009  69  3.298382  1551
3  0003  W004  M001  OP009  63  2.762764  3456
4  0004  W002  M001  OP005  95  5.949591  2805

In [102]:
operations_df = pd.DataFrame(rows,columns=["operation_id","work_order_id","machine_id","operator_id","parts","cutting_time","rpm"])

In [103]:
#operations_df.to_sql("operations",engine,if_exists="append",index=False)

In [104]:
tools_df.head()

  tool_id       tool_type insert_shape  chip_breaker
0    T001  Diamond Insert   Triangular         False
1    T002  Diamond Insert      Romboid          True
2    T003  Diamond Insert      Romboid         False
3    T004  Diamond Insert   Triangular          True
4    T005  Diamond Insert      Romboid         False

In [105]:
operations_df.head()

  operation_id work_order_id machine_id operator_id  parts  cutting_time   rpm
0         0000          W004       M003       OP003     89      4.310778  3316
1         0001          W005       M006       OP007     21      6.302662  2103
2         0002          W009       M001       OP009     69      3.298382  1551
3         0003          W004       M001       OP009     63      2.762764  3456
4         0004          W002       M001       OP005     95      5.949591  2805

## 3. Operations Data Generation

In [106]:
operation_tool_rows= []

In [107]:
for operation_id in operations_df["operation_id"]:
    num_tools = random.randint(1, 3)
    selected_tools = random.sample(tools_df["tool_id"].tolist(), num_tools)

    for tool_id in selected_tools:
        operation_tool_rows.append([operation_id, tool_id])

## 4. Operation-Tool Relationships

In [108]:
operation_tools_df= pd.DataFrame(operation_tool_rows,columns=["operation_id","tool_id"])

In [109]:
operation_tools_df.shape

(205, 2)

In [110]:
#operation_tools_df.to_sql("operation_tools",engine,if_exists="append",index=False)

In [111]:
tool_positions_df=pd.read_sql("SELECT * FROM tool_positions",engine)

In [112]:
tool_positions_df.head()

  position_id tool_id  position_number
0        P001    T001                1
1        P002    T001                2
2        P003    T001                3
3        P004    T002                1
4        P005    T002                2

In [113]:
operation_tools_df = pd.read_sql("SELECT * FROM operation_tools",engine)

In [114]:
operation_tools_df.head()

  operation_id tool_id
0         0000    T008
1         0001    T001
2         0001    T007
3         0002    T007
4         0003    T004

In [115]:
tool_positions_df.head()

  position_id tool_id  position_number
0        P001    T001                1
1        P002    T001                2
2        P003    T001                3
3        P004    T002                1
4        P005    T002                2

In [116]:
operation_positions_df=operation_tools_df.merge(
    tool_positions_df,
    on="tool_id",
    how="inner"
)

In [117]:
operation_positions_df.head()

  operation_id tool_id position_id  position_number
0         0000    T008        P027                1
1         0000    T008        P028                2
2         0000    T008        P029                3
3         0001    T001        P001                1
4         0001    T001        P002                2

In [118]:
operation_positions_df = operation_positions_df.groupby(
    ["operation_id", "tool_id"]
).sample(n=1)

In [119]:
operation_positions_df.head(10)

   operation_id tool_id position_id  position_number
0          0000    T008        P027                1
5          0001    T001        P003                3
7          0001    T007        P024                2
13         0002    T007        P026                4
16         0003    T004        P014                3
18         0003    T006        P020                2
24         0004    T005        P018                4
31         0005    T001        P001                1
25         0005    T008        P027                1
28         0005    T009        P030                1

In [120]:
operations_df=pd.read_sql("SELECT * FROM operations",engine)

In [121]:
wear_base_df=operation_positions_df.merge(
    operations_df,
    on="operation_id",
    how="left"
)

In [122]:
wear_base_df.head(10)

,operation_id,tool_id,position_id,position_number,work_order_id,machine_id,operator_id,parts,cutting_time,rpm
0,0000,T008,P027,1,W007,M002,OP001,68,1.80,2114
1,0001,T001,P003,3,W006,M004,OP004,61,3.17,3491
2,0001,T007,P024,2,W006,M004,OP004,61,3.17,3491
3,0002,T007,P026,4,W002,M001,OP006,36,2.12,2198
4,0003,T004,P014,3,W006,M005,OP002,93,8.10,1160
5,0003,T006,P020,2,W006,M005,OP002,93,8.10,1160
6,0004,T005,P018,4,W005,M007,OP001,79,3.18,1198
7,0005,T001,P001,1,W004,M001,OP004,83,7.39,883
8,0005,T008,P027,1,W004,M001,OP004,83,7.39,883
9,0005,T009,P030,1,W004,M001,OP004,83,7.39,883

## 5. Wear Measurement Generation

In [123]:
wear_values = []

for _, row in wear_base_df.iterrows():
    wear = (
        row["parts"] * 0.001
        + row["cutting_time"] * 0.01
        + random.uniform(0, 0.03)
    )
    
    wear_values.append(wear)

In [124]:
wear_base_df["wear_mm"]=wear_values

In [125]:
wear_base_df.head()

,operation_id,tool_id,position_id,position_number,work_order_id,machine_id,operator_id,parts,cutting_time,rpm,wear_mm
0,0000,T008,P027,1,W007,M002,OP001,68,1.80,2114,0.089538
1,0001,T001,P003,3,W006,M004,OP004,61,3.17,3491,0.104813
2,0001,T007,P024,2,W006,M004,OP004,61,3.17,3491,0.104478
3,0002,T007,P026,4,W002,M001,OP006,36,2.12,2198,0.067199
4,0003,T004,P014,3,W006,M005,OP002,93,8.10,1160,0.188850

In [126]:
conditions=[]

for wear in wear_base_df["wear_mm"]:
    if wear<0.10:
        condition="Normal"
    elif wear<0.20:
        condition="Slight Whitening"
    else:
        condition="Visible Wear"

conditions.append(condition)

In [127]:
conditions = []

for wear in wear_base_df["wear_mm"]:
    if wear < 0.10:
        condition = "Normal"
    elif wear < 0.20:
        condition = "Slight Whitening"
    else:
        condition = "Visible Wear"

    conditions.append(condition)

print(len(conditions))

202

In [128]:
wear_base_df["visual_condition"] = conditions

In [129]:
wear_base_df.head(10)

,operation_id,tool_id,position_id,position_number,work_order_id,machine_id,operator_id,parts,cutting_time,rpm,wear_mm,visual_condition
0,0000,T008,P027,1,W007,M002,OP001,68,1.80,2114,0.089538,Normal
1,0001,T001,P003,3,W006,M004,OP004,61,3.17,3491,0.104813,Slight Whitening
2,0001,T007,P024,2,W006,M004,OP004,61,3.17,3491,0.104478,Slight Whitening
3,0002,T007,P026,4,W002,M001,OP006,36,2.12,2198,0.067199,Normal
4,0003,T004,P014,3,W006,M005,OP002,93,8.10,1160,0.188850,Slight Whitening
5,0003,T006,P020,2,W006,M005,OP002,93,8.10,1160,0.191794,Slight Whitening
6,0004,T005,P018,4,W005,M007,OP001,79,3.18,1198,0.114943,Slight Whitening
7,0005,T001,P001,1,W004,M001,OP004,83,7.39,883,0.162091,Slight Whitening
8,0005,T008,P027,1,W004,M001,OP004,83,7.39,883,0.161555,Slight Whitening
9,0005,T009,P030,1,W004,M001,OP004,83,7.39,883,0.176521,Slight Whitening

In [130]:
wear_base_df.columns

Index(['operation_id', 'tool_id', 'position_id', 'position_number',
       'work_order_id', 'machine_id', 'operator_id', 'parts', 'cutting_time',
       'rpm', 'wear_mm', 'visual_condition'],
      dtype='str')

In [131]:
wear_measurements_df = wear_base_df[
    ["position_id", "operation_id", "wear_mm", "visual_condition"]
].copy()

In [132]:
wear_measurements_df.head()

  position_id operation_id   wear_mm  visual_condition
0        P027         0000  0.089538            Normal
1        P003         0001  0.104813  Slight Whitening
2        P024         0001  0.104478  Slight Whitening
3        P026         0002  0.067199            Normal
4        P014         0003  0.188850  Slight Whitening

## 6. Date Generation

In [133]:
from datetime import datetime, timedelta

start_date = datetime(2026, 1, 1)

dates = []

for i in range(len(wear_measurements_df)):
    dates.append(start_date + timedelta(days=i))

In [134]:
wear_measurements_df["mesaurement_date"] = dates

In [135]:
wear_measurements_df.head()

  position_id operation_id   wear_mm  visual_condition mesaurement_date
0        P027         0000  0.089538            Normal       2026-01-01
1        P003         0001  0.104813  Slight Whitening       2026-01-02
2        P024         0001  0.104478  Slight Whitening       2026-01-03
3        P026         0002  0.067199            Normal       2026-01-04
4        P014         0003  0.188850  Slight Whitening       2026-01-05

## 7. PostgreSQL Data Insertion

In [141]:
#wear_measurements_df.to_sql("wear_measurements",engine,if_exists="append",index=False)

In [137]:
wear_measurements_df["measurement_date"] = dates

In [138]:
wear_measurements_df = wear_measurements_df.drop(columns=["mesaurement_date"])

In [139]:
wear_measurements_df.columns

Index(['position_id', 'operation_id', 'wear_mm', 'visual_condition',
       'measurement_date'],
      dtype='str')

In [140]:
pd.read_sql(
    "SELECT COUNT(*) FROM wear_measurements",
    engine
)

   count
0    404